// Mocks generated by Mockito 5.4.4 from annotations
// in lifecoach/test/retrofit_client_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;

import 'package:lifecoach/infrastructure/ws/models/requests/chat_request/chat_request.dart'
    as _i13;
import 'package:lifecoach/infrastructure/ws/models/responses/authentication_response/prepare_verification_response/prepare_verification_response.dart'
    as _i5;
import 'package:lifecoach/infrastructure/ws/models/responses/authentication_response/sign_in_response/sign_in_response.dart'
    as _i2;
import 'package:lifecoach/infrastructure/ws/models/responses/authentication_response/sign_up_response/sign_up_response.dart'
    as _i4;
import 'package:lifecoach/infrastructure/ws/models/responses/authentication_response/verification_response.dart'
    as _i6;
import 'package:lifecoach/infrastructure/ws/models/responses/created_goal_response/created_goal_response.dart'
    as _i8;
import 'package:lifecoach/infrastructure/ws/models/responses/delete_goal_response/delete_goal_response.dart'
    as _i10;
import 'package:lifecoach/infrastructure/ws/models/responses/goals_response/goals_response.dart'
    as _i7;
import 'package:lifecoach/infrastructure/ws/models/responses/sign_out_response/sign_out_response.dart'
    as _i3;
import 'package:lifecoach/infrastructure/ws/models/responses/updated_goal_response/updated_goal_response.dart'
    as _i9;
import 'package:lifecoach/infrastructure/ws/rest/retrofit_client/retrofit_client.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:models/models.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSignInResponse_0 extends _i1.SmartFake
    implements _i2.SignInResponse {
  _FakeSignInResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSignOutResponse_1 extends _i1.SmartFake
    implements _i3.SignOutResponse {
  _FakeSignOutResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSignUpResponse_2 extends _i1.SmartFake
    implements _i4.SignUpResponse {
  _FakeSignUpResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePrepareVerificationResponse_3 extends _i1.SmartFake
    implements _i5.PrepareVerificationResponse {
  _FakePrepareVerificationResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerificationResponse_4 extends _i1.SmartFake
    implements _i6.VerificationResponse {
  _FakeVerificationResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGoalsResponse_5 extends _i1.SmartFake implements _i7.GoalsResponse {
  _FakeGoalsResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreatedGoalResponse_6 extends _i1.SmartFake
    implements _i8.CreatedGoalResponse {
  _FakeCreatedGoalResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdatedGoalResponse_7 extends _i1.SmartFake
    implements _i9.UpdatedGoalResponse {
  _FakeUpdatedGoalResponse_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteGoalResponse_8 extends _i1.SmartFake
    implements _i10.DeleteGoalResponse {
  _FakeDeleteGoalResponse_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RetrofitClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockRetrofitClient extends _i1.Mock implements _i11.RetrofitClient {
  MockRetrofitClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i2.SignInResponse> signEmail(String? identifier) =>
      (super.noSuchMethod(
        Invocation.method(
          #signEmail,
          [identifier],
        ),
        returnValue:
            _i12.Future<_i2.SignInResponse>.value(_FakeSignInResponse_0(
          this,
          Invocation.method(
            #signEmail,
            [identifier],
          ),
        )),
      ) as _i12.Future<_i2.SignInResponse>);

  @override
  _i12.Future<_i2.SignInResponse> signIn(
    String? identifier,
    String? password,
    String? strategy,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [
            identifier,
            password,
            strategy,
          ],
        ),
        returnValue:
            _i12.Future<_i2.SignInResponse>.value(_FakeSignInResponse_0(
          this,
          Invocation.method(
            #signIn,
            [
              identifier,
              password,
              strategy,
            ],
          ),
        )),
      ) as _i12.Future<_i2.SignInResponse>);

  @override
  _i12.Future<_i3.SignOutResponse> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue:
            _i12.Future<_i3.SignOutResponse>.value(_FakeSignOutResponse_1(
          this,
          Invocation.method(
            #signOut,
            [],
          ),
        )),
      ) as _i12.Future<_i3.SignOutResponse>);

  @override
  _i12.Future<_i4.SignUpResponse> signUp(
    String? emailAddress,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [
            emailAddress,
            password,
          ],
        ),
        returnValue:
            _i12.Future<_i4.SignUpResponse>.value(_FakeSignUpResponse_2(
          this,
          Invocation.method(
            #signUp,
            [
              emailAddress,
              password,
            ],
          ),
        )),
      ) as _i12.Future<_i4.SignUpResponse>);

  @override
  _i12.Future<_i5.PrepareVerificationResponse> prepare(
    String? id,
    String? strategy,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #prepare,
          [
            id,
            strategy,
          ],
        ),
        returnValue: _i12.Future<_i5.PrepareVerificationResponse>.value(
            _FakePrepareVerificationResponse_3(
          this,
          Invocation.method(
            #prepare,
            [
              id,
              strategy,
            ],
          ),
        )),
      ) as _i12.Future<_i5.PrepareVerificationResponse>);

  @override
  _i12.Future<_i6.VerificationResponse> verify(
    String? id,
    String? code,
    String? strategy,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verify,
          [
            id,
            code,
            strategy,
          ],
        ),
        returnValue: _i12.Future<_i6.VerificationResponse>.value(
            _FakeVerificationResponse_4(
          this,
          Invocation.method(
            #verify,
            [
              id,
              code,
              strategy,
            ],
          ),
        )),
      ) as _i12.Future<_i6.VerificationResponse>);

  @override
  _i12.Stream<String> sendEnglishWebChatMessage(
          _i13.ChatRequest? chatRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEnglishWebChatMessage,
          [chatRequest],
        ),
        returnValue: _i12.Stream<String>.empty(),
      ) as _i12.Stream<String>);

  @override
  _i12.Stream<String> sendUkrainianWebChatMessage(
          _i13.ChatRequest? chatRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendUkrainianWebChatMessage,
          [chatRequest],
        ),
        returnValue: _i12.Stream<String>.empty(),
      ) as _i12.Stream<String>);

  @override
  _i12.Stream<String> sendEnglishAndroidAnonymousChatMessage(
          _i13.ChatRequest? chatRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEnglishAndroidAnonymousChatMessage,
          [chatRequest],
        ),
        returnValue: _i12.Stream<String>.empty(),
      ) as _i12.Stream<String>);

  @override
  _i12.Stream<String> sendEnglishAndroidChatMessage(
          _i13.ChatRequest? chatRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEnglishAndroidChatMessage,
          [chatRequest],
        ),
        returnValue: _i12.Stream<String>.empty(),
      ) as _i12.Stream<String>);

  @override
  _i12.Stream<String> sendUkrainianAndroidChatMessage(
          _i13.ChatRequest? chatRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendUkrainianAndroidChatMessage,
          [chatRequest],
        ),
        returnValue: _i12.Stream<String>.empty(),
      ) as _i12.Stream<String>);

  @override
  _i12.Stream<String> sendUkrainianAndroidAnonymousChatMessage(
          _i13.ChatRequest? chatRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendUkrainianAndroidAnonymousChatMessage,
          [chatRequest],
        ),
        returnValue: _i12.Stream<String>.empty(),
      ) as _i12.Stream<String>);

  @override
  _i12.Stream<String> sendEnglishIosChatMessage(
          _i13.ChatRequest? chatRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEnglishIosChatMessage,
          [chatRequest],
        ),
        returnValue: _i12.Stream<String>.empty(),
      ) as _i12.Stream<String>);

  @override
  _i12.Stream<String> sendUkrainianIosChatMessage(
          _i13.ChatRequest? chatRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendUkrainianIosChatMessage,
          [chatRequest],
        ),
        returnValue: _i12.Stream<String>.empty(),
      ) as _i12.Stream<String>);

  @override
  _i12.Stream<String> sendChatMessageOnUnknownPlatform(
          _i13.ChatRequest? chatRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendChatMessageOnUnknownPlatform,
          [chatRequest],
        ),
        returnValue: _i12.Stream<String>.empty(),
      ) as _i12.Stream<String>);

  @override
  _i12.Future<_i7.GoalsResponse> getGoals(
    String? userId,
    int? page,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGoals,
          [
            userId,
            page,
          ],
        ),
        returnValue: _i12.Future<_i7.GoalsResponse>.value(_FakeGoalsResponse_5(
          this,
          Invocation.method(
            #getGoals,
            [
              userId,
              page,
            ],
          ),
        )),
      ) as _i12.Future<_i7.GoalsResponse>);

  @override
  _i12.Future<_i8.CreatedGoalResponse> createGoal(_i14.Goal? goal) =>
      (super.noSuchMethod(
        Invocation.method(
          #createGoal,
          [goal],
        ),
        returnValue: _i12.Future<_i8.CreatedGoalResponse>.value(
            _FakeCreatedGoalResponse_6(
          this,
          Invocation.method(
            #createGoal,
            [goal],
          ),
        )),
      ) as _i12.Future<_i8.CreatedGoalResponse>);

  @override
  _i12.Future<_i9.UpdatedGoalResponse> updateGoal(_i14.Goal? goal) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateGoal,
          [goal],
        ),
        returnValue: _i12.Future<_i9.UpdatedGoalResponse>.value(
            _FakeUpdatedGoalResponse_7(
          this,
          Invocation.method(
            #updateGoal,
            [goal],
          ),
        )),
      ) as _i12.Future<_i9.UpdatedGoalResponse>);

  @override
  _i12.Future<_i10.DeleteGoalResponse> deleteGoal(_i14.Goal? goal) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteGoal,
          [goal],
        ),
        returnValue: _i12.Future<_i10.DeleteGoalResponse>.value(
            _FakeDeleteGoalResponse_8(
          this,
          Invocation.method(
            #deleteGoal,
            [goal],
          ),
        )),
      ) as _i12.Future<_i10.DeleteGoalResponse>);

  @override
  _i12.Future<_i10.DeleteGoalResponse> deleteAccount(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [userId],
        ),
        returnValue: _i12.Future<_i10.DeleteGoalResponse>.value(
            _FakeDeleteGoalResponse_8(
          this,
          Invocation.method(
            #deleteAccount,
            [userId],
          ),
        )),
      ) as _i12.Future<_i10.DeleteGoalResponse>);
}
