name: user_repository
description: Dart package which manages the user domain.
publish_to: none
version: 1.0.0
repository: https://github.com/Turskyi/flutter_life_coaching_ai

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  uuid: ^4.4.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
