name: models
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/Turskyi/flutter_life_coaching_ai

environment:
  sdk: ^3.5.0

dependencies:
  equatable: ^2.0.5
  flutter_translate: ^4.1.0
  formz: ^0.7.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
