name: Code Quality

on: [ push ]

jobs:
  check-code-quality-and-tests:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Get packages
        run: flutter pub get

      - name: Check format errors
        run: dart format --set-exit-if-changed .

      - name: Check lint errors
        run: flutter analyze .

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Turskyi/flutter_life_coaching_ai